Made end screen
AudacityMusic/signup pull request #61
Opened 2024-07-28 02:57 UTC by KingPleather

made end screen

2024-07-30 03:22 UTC, TenType commented on src/screens/EndScreen.js
> +import Ionicons from "@expo/vector-icons/Ionicons";
New dependency added, but looks like there were no `package.json` or `package-lock.json` files committed

2024-07-30 03:26 UTC, TenType requested changes
I don't think all of your changes were committed because the screen is not accessible anywhere in the app and there are missing dependency edits (see my other comment)

Also needs a few more things:
- [x] End screen should show up when the form is submitted
- [ ] There needs to be a way for the user to leave the end screen

2024-07-30 03:26 UTC, TenType commented on src/screens/EndScreen.js
> +import Ionicons from "@expo/vector-icons/Ionicons";
New dependency added, but looks like there were no `package.json` or `package-lock.json` files committed

2024-08-03 16:10 UTC, KingPleather commented on src/screens/EndScreen.js
> +import Ionicons from "@expo/vector-icons/Ionicons";
I dont think i did any installing, i just followed expo's instructions https://icons.expo.fyi/Index/FontAwesome/refresh something like this. Maybe I am wrong though, and if so, how do i add the changes cuz its not showing up in the github desktop.

2024-08-03 18:59 UTC, TenType commented on src/screens/EndScreen.js
> +import Ionicons from "@expo/vector-icons/Ionicons";
Never mind, the vector icons library is part of the [default expo package](https://docs.expo.dev/guides/icons/), so you're good

2024-08-05 02:30 UTC, TenType approved these changes
Further end screen improvements in #65

2024-08-05 02:30 UTC, merged