No Internet Banner
AudacityMusic/signup pull request #63
Opened 2024-07-30 03:10 UTC by Heliophist

Added NoInternetBanner.js to components folder.
Modified app.js to scan for wifi/internet presence.
Installed some stuff from react native community netinfo.

2024-07-30 18:09 UTC, TenType requested changes
iOS: White gap at the top of the screen
Android: No gap but the banner is not visible

2024-07-30 18:09 UTC, TenType commented on App.js
> +        {!isConnected && <NoInternetBanner />}
Banner is not visible on Android, even if this line is just `<NoInternetBanner />` without any conditional checks. The banner shows up for a split second when navigating backwards to another screen, but it does not persist.

2024-08-10 05:51 UTC, TenType commented
Not resolved - still has the gap on iOS
<img width="362" alt="image" src="https://github.com/user-attachments/assets/d6c43910-2bea-4c9f-838a-6fe2a7a3ca7c">

2024-08-21 05:45 UTC, Heliophist commented
On my end, the code works I can send a screenshot.
However, I have had to merge mine with the updated app.js, so things may be a little messy,

2025-06-22 06:05 UTC, closed without merging