Other forms
AudacityMusic/signup pull request #77
Opened 2024-09-03 00:20 UTC by Pramad712

Dance Club & Request Concert Functionality added!
(I tried to find a more gender-neutral icon for the dance club thing but the only other ones were a ball dance and pole dancing)
(there is also one small ui issue, that is the gap between each of the music pieces' text boxes, aka bottom margin, is 20, though in the code it is set to 0 (on all but the last one ofc to add a margin between it and the next question). 10 instead of 0 also doesn't work.)

2024-09-04 17:03 UTC, TenType requested changes
Minor edits for readability and future debugging purposes (see discord)

Not fully tested yet

2024-09-04 17:04 UTC, TenType commented on src/utils/index.js
> +    console.log(response);
This is just one example; there are more places where we need to use `alertError`

2024-09-08 01:16 UTC, Pramad712 commented on src/utils/index.js
> +    console.log(response);
fixed

2024-09-11 00:50 UTC, TenType approved these changes

2024-09-11 00:50 UTC, merged